import { Platform, StyleSheet } from "react-native";

export const C = {
  blue: "#2465c7",
  ink: "#1c2b3e",
  muted: "#8290a3",
  line: "#e2e9f3",
  canvas: "#f4f7fb",
  green: "#358562",
};
export const s = StyleSheet.create({
  passwordField: { flexDirection: "row", alignItems: "center", position: "relative" },
  passwordInput: { flex: 1, minWidth: 0 },
  passwordSpacing: { paddingRight: 72 },
  passwordToggle: { position: "absolute", right: 4, minWidth: 60, minHeight: 44, alignItems: "center", justifyContent: "center", borderRadius: 8 },
  passwordToggleText: { color: C.blue, fontSize: 12, fontWeight: "600" },
  hidden: { display: "none" },
  quantityValue: {
    fontSize: 18,
    fontWeight: "600",
    color: C.ink,
    textAlign: "center",
  },
  tinyPayment: { padding: 8, gap: 2 },
  tinyField: { marginVertical: 2, gap: 3 },
  tinyInput: { minHeight: 40, paddingVertical: 6, fontSize: 18 },
  tinyChange: { fontSize: 18 },
  tinyBack: { minHeight: 28 },
  flex: { flex: 1, minHeight: 0, minWidth: 0 },
  screen: { flex: 1, backgroundColor: C.canvas, overflow: "hidden" },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.canvas,
  },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10 },
  row: { flexDirection: "row", gap: 6, alignItems: "center" },
  bold: { fontWeight: "700" },
  button: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: C.blue,
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.blue,
  },
  buttonText: { color: "white", fontSize: 13, fontWeight: "600" },
  secondaryButton: { backgroundColor: "white", borderColor: "#dce4ef" },
  secondaryText: { color: C.blue },
  smallButton: { paddingHorizontal: 10, paddingVertical: 8, minHeight: 38 },
  disabled: { opacity: 0.4 },
  pressed: { opacity: 0.7 },
  field: { gap: 5, marginVertical: 5 },
  fieldLabel: { fontSize: 12, fontWeight: "600", color: "#43546b" },
  input: {
    borderWidth: 1,
    borderColor: "#dce4ef",
    borderRadius: 9,
    backgroundColor: "white",
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: C.ink,
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 1.5,
    fontWeight: "700",
    color: "#5279ad",
    marginBottom: 6,
  },
  subtitle: { color: C.muted, fontSize: 12, lineHeight: 18 },
  muted: { color: C.muted, fontSize: 10 },
  link: { color: C.blue, fontSize: 12, fontWeight: "600" },
  topbar: {
    flexDirection: "row",
    alignItems: "center",
    height: 54,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    paddingHorizontal: 10,
    gap: 6,
  },
  smallBrand: {
    width: 30,
    height: 30,
    borderRadius: 9,
    backgroundColor: C.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  smallBrandLetters: { color: "white", fontWeight: "700", fontSize: 12 },
  brandName: { color: "#1e3761", fontSize: 13, fontWeight: "700" },
  headerCaption: { fontSize: 9, color: C.muted, marginTop: 2 },
  headerButton: {
    minWidth: 38,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  headerIcon: { color: C.blue, fontSize: 22 },
  loginScroll: {
    flexGrow: 1,
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  loginCard: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "white",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    padding: 26,
    gap: 12,
  },
  brandMark: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: C.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  brandLetters: { color: "white", fontSize: 18, fontWeight: "700" },
  loginBrand: {
    color: "#5279ad",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
  },
  loginTitle: { fontSize: 28, fontWeight: "700", color: C.ink },
  loginFooter: {
    color: C.muted,
    fontSize: 11,
    textAlign: "center",
    marginTop: 10,
  },
  cashierMain: { flex: 1, minHeight: 0, padding: 10, gap: 8 },
  landscapeMain: { paddingVertical: 6, gap: 5 },
  cashierHeading: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pageTitle: {
    fontSize: 23,
    color: C.ink,
    fontWeight: "700",
    letterSpacing: -0.6,
  },
  cashBadge: {
    fontSize: 10,
    color: C.green,
    backgroundColor: "#f0f8f5",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 5,
  },
  steps: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 6,
    paddingVertical: 4,
  },
  step: { flexDirection: "row", alignItems: "center", gap: 5 },
  stepNumber: {
    width: 21,
    height: 21,
    borderRadius: 11,
    backgroundColor: "#e6ecf4",
    alignItems: "center",
    justifyContent: "center",
  },
  activeStep: { backgroundColor: C.blue },
  stepDigit: { fontSize: 10, fontWeight: "700", color: C.muted },
  activeStepDigit: { color: "white" },
  stepTitle: { fontSize: 10, color: "#61758e", fontWeight: "500" },
  checkoutContent: { flex: 1, minHeight: 0, minWidth: 0 },
  checkout: { flex: 1, minHeight: 0, gap: 8 },
  checkoutWide: { flexDirection: "row" },
  panel: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    overflow: "hidden",
  },
  panelTitle: { color: C.ink, fontSize: 16, fontWeight: "700" },
  selection: { flex: 1, minHeight: 0, padding: 10, gap: 8 },
  productGrid: { flex: 1, minHeight: 0, flexDirection: "row", gap: 8 },
  productTile: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    backgroundColor: "white",
    borderWidth: 1.5,
    borderColor: "#e4ebf4",
    borderRadius: 10,
    padding: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  selectedTile: { backgroundColor: "#f3f8ff", borderColor: C.blue },
  selectionDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 17,
    height: 17,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#d2deee",
    alignItems: "center",
    justifyContent: "center",
  },
  selectedDot: { backgroundColor: C.blue, borderColor: C.blue },
  selectedCheck: { color: "white", fontSize: 10, fontWeight: "700" },
  productTitle: {
    color: "#243e61",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  productUnit: { color: C.muted, fontSize: 10, marginTop: 3 },
  productPrice: { color: C.blue, fontSize: 21, fontWeight: "700" },
  stockBadge: {
    color: C.green,
    backgroundColor: "#edf8f2",
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 10,
    fontWeight: "600",
    alignSelf: "flex-start",
  },
  lowStock: { backgroundColor: "#fff1df", color: "#ad7421" },
  order: { padding: 12, gap: 8, flexShrink: 0 },
  orderWide: { width: 270, justifyContent: "space-between" },
  orderProduct: { fontSize: 12, fontWeight: "600", color: C.ink },
  orderDetails: { flexDirection: "row", alignItems: "center", gap: 12 },
  quantityBox: { flex: 1, gap: 5 },
  stepper: { flexDirection: "row", alignItems: "center", gap: 5 },
  quantityInput: {
    flex: 1,
    justifyContent: "center",
    minWidth: 0,
    minHeight: 40,
    padding: 5,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 8,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "600",
    color: C.ink,
    backgroundColor: "white",
  },
  totalBox: { alignItems: "flex-end", gap: 4 },
  orderAmount: { fontSize: 24, color: "#203e65", fontWeight: "700" },
  emptyOrder: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 6,
  },
  payment: {
    flex: 1,
    minHeight: 0,
    padding: 14,
    justifyContent: "center",
    gap: 6,
  },
  paymentWide: { maxWidth: 600, width: "100%", alignSelf: "center" },
  paymentAmount: {
    backgroundColor: "#f1f6fe",
    padding: 16,
    borderRadius: 10,
    marginVertical: 6,
    gap: 5,
  },
  compactAmount: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 8,
    marginVertical: 0,
  },
  amountLabel: { color: "#6a84a7", fontSize: 11 },
  amountDue: { color: C.blue, fontSize: 34, fontWeight: "700" },
  compactDue: { fontSize: 24 },
  cashInput: { fontSize: 22, fontWeight: "600" },
  cashShortcuts: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  shortcut: { width: "31.8%" },
  changeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
  },
  changeAmount: { color: C.green, fontSize: 23, fontWeight: "700" },
  paymentHint: { color: "#ad7421", fontSize: 10 },
  backButton: { minHeight: 34, alignItems: "center", justifyContent: "center" },
  receiptScreen: { flex: 1, minHeight: 0, gap: 6, alignItems: "center" },
  saleComplete: { color: C.green, fontSize: 19, fontWeight: "700" },
  receiptPreview: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    alignItems: "center",
    overflow: "hidden",
  },
  receiptPosition: { position: "absolute", top: 0, width: 300 },
  receiptPaper: {
    width: 300,
    padding: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: "white",
    gap: 5,
  },
  receiptBrand: {
    color: C.ink,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  receiptCenter: { color: "#40516a", fontSize: 10, textAlign: "center" },
  receiptRule: {
    borderTopWidth: 1,
    borderStyle: "dashed",
    borderColor: "#b6c0ce",
    marginVertical: 8,
  },
  receiptRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginVertical: 2,
  },
  receiptText: {
    color: "#253c56",
    fontSize: 10,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  receiptTotal: { fontSize: 15, fontWeight: "700" },
  receiptActions: {
    flexDirection: "row",
    gap: 8,
    width: "100%",
    flexShrink: 0,
  },
  adminMain: {
    padding: 16,
    gap: 12,
    width: "100%",
    maxWidth: 1100,
    alignSelf: "center",
  },
  metrics: { flexDirection: "row", gap: 10, marginTop: 6 },
  metric: { flex: 1, padding: 14, gap: 7 },
  metricValue: { color: C.ink, fontSize: 23, fontWeight: "700" },
  metricCaption: { color: C.muted, fontSize: 9 },
  sectionTitle: { color: C.ink, fontSize: 16, fontWeight: "600", marginTop: 8 },
  inventoryCards: { gap: 12 },
  inventoryWide: { flexDirection: "row" },
  inventoryCard: {
    flexGrow: 1,
    flexShrink: 1,
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    gap: 12,
  },
  inventoryDetail: { flex: 1, minWidth: 0, gap: 4 },
  inventoryTitle: {
    color: C.ink,
    fontSize: 18,
    fontWeight: "700",
    marginTop: 4,
  },
  stockValueRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "baseline",
    marginVertical: 7,
  },
  stockValue: { color: C.ink, fontSize: 33, fontWeight: "700" },
  inventoryFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 9,
    borderTopWidth: 1,
    borderColor: "#edf1f7",
  },
  priceLabel: { color: "#61758e", fontSize: 10 },
  tableHeading: { padding: 15, gap: 4 },
  tableLabels: {
    flexDirection: "row",
    gap: 10,
    padding: 12,
    backgroundColor: "#fafbfd",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#edf1f7",
  },
  tableLabel: {
    color: "#91a0b3",
    fontSize: 8,
    letterSpacing: 0.5,
    fontWeight: "600",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    gap: 10,
    borderBottomWidth: 1,
    borderColor: "#f0f3f8",
  },
  transactionTitle: { color: "#43546b", fontSize: 11, fontWeight: "600" },
  transactionMeta: {
    fontSize: 9,
    color: C.muted,
    marginTop: 4,
    lineHeight: 14,
  },
  transactionTotal: {
    color: "#27466e",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
  },
  receiptLink: { color: C.blue, fontSize: 9, marginTop: 5, textAlign: "right" },
  stockTotal: { alignItems: "flex-end" },
  positive: {
    color: C.green,
    backgroundColor: "#edf8f2",
    padding: 5,
    borderRadius: 5,
    fontSize: 12,
    fontWeight: "700",
  },
  tableEmpty: {
    padding: 20,
    color: C.muted,
    textAlign: "center",
    fontSize: 12,
  },
  pagination: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  stockNotice: {
    position: "absolute",
    top: 58,
    left: 10,
    right: 10,
    zIndex: 40,
    backgroundColor: "#fffaed",
    borderWidth: 1,
    borderColor: "#e9d294",
    borderRadius: 10,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  noticeTitle: { fontSize: 12, fontWeight: "700", color: "#856025" },
  noticeCopy: { fontSize: 10, color: "#a08758", marginTop: 4 },
  toast: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    zIndex: 50,
    backgroundColor: "#fff0f1",
    borderRadius: 9,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toastText: { flex: 1, fontSize: 12, color: "#ba4754" },
  errorText: { color: "#ba4754", fontSize: 12, lineHeight: 18 },
  successToast: { backgroundColor: "#edf8f2" },
  successText: { color: C.green },
  dismissButton: {
    minWidth: 32,
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "#18334e88",
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    width: "100%",
    maxWidth: 430,
    maxHeight: "95%",
    backgroundColor: "white",
    borderRadius: 14,
    overflow: "hidden",
  },
  modalContent: { padding: 20, gap: 15 },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
  },
  restockPreview: {
    backgroundColor: "#f1f6fe",
    padding: 14,
    borderRadius: 8,
    color: "#5279ad",
    fontSize: 12,
  },
});
