-- Run this once on an existing waterproject database before using the new frontend.
ALTER TABLE Product ADD COLUMN IF NOT EXISTS ProductUnit VARCHAR(50) NULL AFTER Stocks;
ALTER TABLE Product ADD COLUMN IF NOT EXISTS MinStock INT NOT NULL DEFAULT 10 AFTER ProductUnit;
ALTER TABLE Product ADD COLUMN IF NOT EXISTS UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER MinStock;
